experiment_folder: freq/beta

root_dir: /vol/megdata/raw/

clamp: 5.0
filter: True
filter_low: 13.0
filter_high: 30.0

batch_size: 128
learning_rate: 1e-4
num_epochs: 100


channel_dropout: True
p_channel_dropout: 0.5
attention: True
subject_layer: True