experiment_folder: freq/theta

root_dir: /vol/megdata/raw/

clamp: 5.0
filter: True
filter_low: 4.0
filter_high: 8.0

batch_size: 128
learning_rate: 1e-4
num_epochs: 100


channel_dropout: True
p_channel_dropout: 0.5
attention: True
subject_layer: True