experiment_folder: exp_no_dropout

root_dir: /vol/megdata/raw/

clamp: 5.0

batch_size: 192
learning_rate: 1e-4
num_epochs: 150


channel_dropout: False
p_channel_dropout: 0.2
attention: True
subject_layer: True