experiment_folder: exp

root_dir: /home/tu/tu_tu/tu_zxolg48/data/raw/

clamp: 5.0

batch_size: 128
learning_rate: 1e-4
num_epochs: 100


channel_dropout: True
p_channel_dropout: 0.4
subject_layer: True