experiment_folder: MT/subj_11

root_dir: /vol/megdata/raw/

clamp: 5.0
spectrogram: False
filter: False
filter_low: 0.3
filter_high: 8.0

transform: True

batch_size: 64
learning_rate: 1e-4
num_epochs: 500


channel_dropout: False
p_channel_dropout: 0.2
attention: True
subject_layer: True

subjects: [11]